### ISSUE TITLE
Approve Appointment

### ISSUE THREAD

**Issue by VivianLVenter** [undecidables/Documentation#7]
This use case is for approving an appointment after it has been made. Appointment can only be approved by a staff member (lecturer).

**Comment by VivianLVenter** [comment]
Only need to add the use case diagram

**Comment by VivianLVenter** [comment]
Still need to do the process specification

**Comment by VivianLVenter** [comment]
Renette will you just review my process specification for approve and disapprove appointment

**Comment by Mistborn94** [comment]
It seems fine.
